name: module_data

on:
  push:
    branches:
      - '**'
    paths:
      - "data/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.pull_request.number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  data:
    uses: ./.github/workflows/test.yml
    with:
      module: 'data'
    secrets: inherit
